blank_issues_enabled: false
contact_links:
  - name: Вопросы и обсуждения
    url: https://github.com/cdek-it/project-hub/discussions
    about: Задайте вопрос, обсудите идеи или поделитесь опытом использования дизайн-системы
